# Generated by Django 5.2 on 2025-04-11 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spam_check', '0002_phonenumbermeta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone_number',
            field=models.CharField(db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='phonenumbermeta',
            name='phone_number',
            field=models.CharField(db_index=True, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='spamreport',
            name='phone_number',
            field=models.CharField(db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(db_index=True, max_length=10, unique=True),
        ),
    ]
